<html>
<head><meta charset="utf-8"><title>python question · general · Zulip Chat Archive</title></head>
<h2>Stream: <a href="http://127.0.0.1:4000/html/stream/3-general/index.html">general</a></h2>
<h3>Topic: <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html">python question</a></h3>

<hr>


<head><link href="http://127.0.0.1:4000/style.css" rel="stylesheet"></head>

<a name="456"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/3-general/topic/python%20question/near/456" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Matt Long <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html#456">(Jan 15 2020 at 18:46)</a>:</h4>
<p>this is really a python question</p>



<a name="60915"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/3-general/topic/python%20question/near/60915" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Hyunggyu Lim <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html#60915">(Aug 04 2022 at 16:07)</a>:</h4>
<p>Hi all, <br>
I'm running <span class="user-mention" data-user-id="28">@Kristen Krumhardt</span> 's CESM-FOSI postprocessing code. It seems to be running in Kristen's id in the past on Casper. But it is not working for me (/glade/u/home/hglim/analysis/FEISTY/NOTE/kristenk/fish-offline-kristens_branch/notebooks/DPLE_FEISTY_upper_fields.ipynb). Anyone have any thoughts? </p>
<p>I copied Kristen's environment from /glade/u/home/kristenk/my-cesm-experiment/environment.yml<br>
then did as below.<br>
conda env create -f environment.yml</p>



<a name="60916"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/3-general/topic/python%20question/near/60916" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Hyunggyu Lim <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html#60916">(Aug 04 2022 at 16:08)</a>:</h4>
<p>Error messages look like this when running (/glade/u/home/hglim/analysis/FEISTY/NOTE/kristenk/fish-offline-kristens_branch/notebooks/DPLE_FEISTY_upper_fields.ipynb) but we don't know yet how can we deal with.<br>
<a href="../../../user_uploads/2/70/alnmK3aHpsha8oY56gdSCqDS/Screen-Shot-2022-08-04-at-12.07.40.png">Screen-Shot-2022-08-04-at-12.07.40.png</a> <a href="../../../user_uploads/2/fe/E4DCerm7H0LJFoji5lqzXvtB/Screen-Shot-2022-08-04-at-12.08.05.png">Screen-Shot-2022-08-04-at-12.08.05.png</a>  <a href="../../../user_uploads/2/d1/9tyq_DPt4AXn-q3EsXvNXZF8/Screen-Shot-2022-08-04-at-12.08.19.png">Screen-Shot-2022-08-04-at-12.08.19.png</a></p>
<div class="message_inline_image"><a href="../../../user_uploads/2/70/alnmK3aHpsha8oY56gdSCqDS/Screen-Shot-2022-08-04-at-12.07.40.png" title="Screen-Shot-2022-08-04-at-12.07.40.png"><img src="../../../user_uploads/2/70/alnmK3aHpsha8oY56gdSCqDS/Screen-Shot-2022-08-04-at-12.07.40.png"></a></div><div class="message_inline_image"><a href="../../../user_uploads/2/fe/E4DCerm7H0LJFoji5lqzXvtB/Screen-Shot-2022-08-04-at-12.08.05.png" title="Screen-Shot-2022-08-04-at-12.08.05.png"><img src="../../../user_uploads/2/fe/E4DCerm7H0LJFoji5lqzXvtB/Screen-Shot-2022-08-04-at-12.08.05.png"></a></div><div class="message_inline_image"><a href="../../../user_uploads/2/d1/9tyq_DPt4AXn-q3EsXvNXZF8/Screen-Shot-2022-08-04-at-12.08.19.png" title="Screen-Shot-2022-08-04-at-12.08.19.png"><img src="../../../user_uploads/2/d1/9tyq_DPt4AXn-q3EsXvNXZF8/Screen-Shot-2022-08-04-at-12.08.19.png"></a></div>



<a name="60918"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/3-general/topic/python%20question/near/60918" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Hyunggyu Lim <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html#60918">(Aug 04 2022 at 16:11)</a>:</h4>
<p>by command "dso_anoms.load()"</p>



<a name="61040"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/3-general/topic/python%20question/near/61040" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Deepak Cherian <a href="http://127.0.0.1:4000/html/stream/3-general/topic/python.20question.html#61040">(Aug 05 2022 at 15:06)</a>:</h4>
<p>This is a 142GB array. If you didn't request more than that when you opened your session, it will fail.</p>
<p>If you want to save to disk, use <code>to_zarr</code>. We've generally found that distributed writes of large datasets to netCDF tend to fail.</p>



<hr><p>Last updated: May 16 2025 at 17:14 UTC</p>
</html>