<html>
<head><meta charset="utf-8"><title>intake-esm open dataset error · python-questions · Zulip Chat Archive</title></head>
<h2>Stream: <a href="../../..//stream/10-python-questions/index.html">python-questions</a></h2>
<h3>Topic: <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html">intake-esm open dataset error</a></h3>

<hr>


<head><link href="../../../style.css" rel="stylesheet"></head>

<a name="3323"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3323" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3323">(Mar 16 2020 at 17:42)</a>:</h4>
<p>I'm getting this stack track on Casper using NCAR_JobQueue.   It looks like opening an intake-esm catalog is failing.</p>



<a name="3325"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3325" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3325">(Mar 16 2020 at 17:42)</a>:</h4>
<div class="codehilite"><pre><span></span>~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/core.py in to_dataset_dict(self, zarr_kwargs, cdf_kwargs, preprocess, aggregate, storage_options, progressbar)
    390             self.progressbar = progressbar
    391
--&gt; 392         return self._open_dataset()
    393
    394     def _open_dataset(self):

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/core.py in _open_dataset(self)
    501                 progress(futures)
    502
--&gt; 503             dsets = client.gather(futures)
    504
    505         self._ds = {group_id: ds for (group_id, ds) in dsets}

~/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1891                 direct=direct,
   1892                 local_worker=local_worker,
-&gt; 1893                 asynchronous=asynchronous,
   1894             )
   1895

~/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    778         else:
    779             return sync(
--&gt; 780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )
    782

~/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--&gt; 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

~/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--&gt; 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

~/miniconda3/envs/analysis/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733
    734                     try:
--&gt; 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/analysis/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1750                             exc = CancelledError(key)
   1751                         else:
-&gt; 1752                             raise exception.with_traceback(traceback)
   1753                         raise exc
   1754                     if errors == &quot;skip&quot;:

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/core.py in _load_group_dataset()
    582         zarr_kwargs,
    583         cdf_kwargs,
--&gt; 584         preprocess,
    585     )
    586

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in _aggregate()
    162             return ds
    163
--&gt; 164     return apply_aggregation(v)
    165
    166

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in &lt;listcomp&gt;()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in &lt;listcomp&gt;()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in &lt;listcomp&gt;()
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--&gt; 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation()
     91                 zarr_kwargs=zarr_kwargs,
     92                 cdf_kwargs=cdf_kwargs,
---&gt; 93                 preprocess=preprocess,
     94             )
     95             ds.attrs[&#39;intake_esm_varname&#39;] = varname

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in _open_asset()
    194         except Exception as e:
    195             logger.error(f&#39;Failed to open netCDF/HDF dataset.&#39;)
--&gt; 196             raise e
    197
    198     if preprocess is None:

~/miniconda3/envs/analysis/lib/python3.7/site-packages/intake_esm/merge_util.py in _open_asset()
    191         logger.info(f&#39;Opening netCDF/HDF dataset: {root} - protocol: {protocol}&#39;)
    192         try:
--&gt; 193             ds = xr.open_dataset(path, **cdf_kwargs)
    194         except Exception as e:
    195             logger.error(f&#39;Failed to open netCDF/HDF dataset.&#39;)

~/miniconda3/envs/analysis/lib/python3.7/site-packages/xarray/backends/api.py in open_dataset()
    527                 &quot;with engine=&#39;scipy&#39; or &#39;h5netcdf&#39;&quot;
    528             )
--&gt; 529         engine = _get_engine_from_magic_number(filename_or_obj)
    530         if engine == &quot;scipy&quot;:
    531             store = backends.ScipyDataStore(filename_or_obj, **backend_kwargs)

~/miniconda3/envs/analysis/lib/python3.7/site-packages/xarray/backends/api.py in _get_engine_from_magic_number()
    115         magic_number = filename_or_obj[:8]
    116     else:
--&gt; 117         if filename_or_obj.tell() != 0:
    118             raise ValueError(
    119                 &quot;file-like object read/write pointer not at zero &quot;

AttributeError: &#39;FSMap&#39; object has no attribute &#39;tell&#39;
</pre></div>



<a name="3330"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3330" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3330">(Mar 16 2020 at 17:44)</a>:</h4>
<p><span class="user-mention" data-user-id="9">@Brian Bonnlander</span>, that was a bug (introduced by me a few weeks ago <span aria-label="slight smile" class="emoji emoji-1f642" role="img" title="slight smile">:slight_smile:</span>). I fixed it earlier this week-end... </p>
<div class="codehilite"><pre><span></span>python -m pip install git+https://github.com/NCAR/intake-esm.git
</pre></div>



<a name="3332"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3332" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3332">(Mar 16 2020 at 17:45)</a>:</h4>
<p>Update to the HEAD of intake-esm's master branch</p>



<a name="3335"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3335" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3335">(Mar 16 2020 at 17:47)</a>:</h4>
<p>Well, thanks for fixing it!  :)<br>
Trying to write some LENS ocean data to Zarr today...</p>



<a name="3339"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3339" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3339">(Mar 16 2020 at 17:48)</a>:</h4>
<p><span class="user-mention" data-user-id="13">@Anderson Banihirwe</span>  Do I have to restart my kernel after the pip install?   I am still getting the same error using the same kernel.</p>



<a name="3340"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3340" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3340">(Mar 16 2020 at 17:49)</a>:</h4>
<p>Yes, you will need to restart you kernel</p>



<a name="3342"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3342" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3342">(Mar 16 2020 at 17:49)</a>:</h4>
<p>unless you are using the autoreload magic </p>
<div class="codehilite"><pre><span></span><span class="o">%</span><span class="n">laod_ext</span> <span class="n">autoreload</span>
<span class="o">%</span><span class="n">autoreload</span> <span class="mi">2</span>
</pre></div>



<a name="3352"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3352" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3352">(Mar 16 2020 at 17:58)</a>:</h4>
<p>Thanks for your help so far today.   Is it bad when the Dask status tabs stop working in a JupyterHub session?  In the middle of starting the first Zarr store save, the tabs went blank.</p>



<a name="3353"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3353" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3353">(Mar 16 2020 at 17:59)</a>:</h4>
<p>You are welcome!</p>



<a name="3354"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3354" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3354">(Mar 16 2020 at 18:00)</a>:</h4>
<p>I wouldn't worry about the dashboard freezing..</p>



<a name="3356"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3356" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3356">(Mar 16 2020 at 18:01)</a>:</h4>
<p>It tends to happen when a huge amount of information is being sent to the bokeh server on which the dashboard is running on</p>



<a name="3357"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3357" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3357">(Mar 16 2020 at 18:02)</a>:</h4>
<p>If you wait a little bit, things may normalize and the dashboard may go back to working as usual</p>



<a name="3359"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3359" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3359">(Mar 16 2020 at 18:02)</a>:</h4>
<p>OK, but I am also not seeing my Zarr folder growing in size.  After about 5 minutes, it is stuck at around 250K bytes.   Can it sometimes take a while for the in-memory work to finish before starting a write?</p>



<a name="3363"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3363" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3363">(Mar 16 2020 at 18:03)</a>:</h4>
<p>It sounds like something went wrong</p>



<a name="3365"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3365" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3365">(Mar 16 2020 at 18:03)</a>:</h4>
<p>I would restart everything</p>



<a name="3366"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3366" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3366">(Mar 16 2020 at 18:03)</a>:</h4>
<p>tornado.websocket.WebSocketClosedError</p>



<a name="3367"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3367" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3367">(Mar 16 2020 at 18:03)</a>:</h4>
<p>Restart the entire hub?</p>



<a name="3368"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3368" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3368">(Mar 16 2020 at 18:04)</a>:</h4>
<blockquote>
<p>tornado.websocket.WebSocketClosedError</p>
</blockquote>
<p>That's the bokeh server</p>



<a name="3369"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3369" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3369">(Mar 16 2020 at 18:04)</a>:</h4>
<blockquote>
<p>Restart the entire hub? </p>
</blockquote>
<p>Just the kernel</p>



<a name="3370"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3370" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Deepak Cherian <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3370">(Mar 16 2020 at 18:04)</a>:</h4>
<p>How much data are you writing? what is <code>len(dataset.__dask_graph__())</code> → This is the number of tasks. If it's more than 2 million or so, it's too big</p>



<a name="3372"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3372" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3372">(Mar 16 2020 at 18:05)</a>:</h4>
<p>So, I go back to the tab to kill everything, and now the Dask tabs are working again!</p>



<a name="3373"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3373" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3373">(Mar 16 2020 at 18:07)</a>:</h4>
<p>But the number of Dask workers is staying at 2.   Everything looks really slow.   Restart?</p>



<a name="3374"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3374" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3374">(Mar 16 2020 at 18:07)</a>:</h4>
<p>As Deepak pointed out, I would also check the number of tasks before writing to zarr</p>



<a name="3375"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3375" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3375">(Mar 16 2020 at 18:08)</a>:</h4>
<p>Aha, I have to interrupt the Zarr write to find this out, right?   Change the code to print this?</p>



<a name="3376"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3376" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3376">(Mar 16 2020 at 18:09)</a>:</h4>
<blockquote>
<p>But the number of Dask workers is staying at 2. Everything looks really slow. Restart? </p>
</blockquote>
<p>This is normal. You are competing for resources with others...... If the queue is full, dask-workers have to wait to get in</p>



<a name="3377"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3377" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3377">(Mar 16 2020 at 18:10)</a>:</h4>
<p>OK, number of worker just jumped to around 10.</p>



<a name="3378"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3378" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3378">(Mar 16 2020 at 18:10)</a>:</h4>
<p>Things should scale as you get more workers</p>



<a name="3379"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3379" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3379">(Mar 16 2020 at 18:11)</a>:</h4>
<p>Do you have the dashboard open?</p>



<a name="3380"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3380" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3380">(Mar 16 2020 at 18:11)</a>:</h4>
<p>Yes, dashboard is open</p>



<a name="3381"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3381" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3381">(Mar 16 2020 at 18:12)</a>:</h4>
<p>If yes, if you look at the dashboard <code>/status</code> page or <code>progress</code> frame, you should be able to see the number of tasks</p>



<a name="3382"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3382" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3382">(Mar 16 2020 at 18:13)</a>:</h4>
<p>Dask progress tab says total: 27,621.   Is this the tasks?</p>



<a name="3383"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3383" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3383">(Mar 16 2020 at 18:13)</a>:</h4>
<p>Yes</p>



<a name="3384"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3384" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3384">(Mar 16 2020 at 18:13)</a>:</h4>
<p>OK, it looks like progress is being made.</p>



<a name="3389"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3389" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3389">(Mar 16 2020 at 19:01)</a>:</h4>
<p>I can't remember how to authenticate with Globus File Transfer.   Did we use a special account, or our own Google identity, or something else?</p>



<a name="3390"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3390" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3390">(Mar 16 2020 at 19:02)</a>:</h4>
<p>Ah, I meant to make that a private message...sorry.</p>



<a name="3391"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3391" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Kevin Paul <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3391">(Mar 16 2020 at 19:19)</a>:</h4>
<p>You can delete messages. FYI.</p>



<a name="3392"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3392" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3392">(Mar 16 2020 at 19:21)</a>:</h4>
<p>I expected to find a little trash can icon in the upper right menu, but it's not there.</p>



<a name="3393"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3393" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3393">(Mar 16 2020 at 19:22)</a>:</h4>
<p>There is a 10 minute time limit to delete, by default.</p>



<a name="3394"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/3394" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Brian Bonnlander <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#3394">(Mar 16 2020 at 19:23)</a>:</h4>
<p>I think an "organization admin" is needed to change that.</p>



<a name="19284"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19284" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Danica Lombardozzi <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19284">(Oct 12 2020 at 21:10)</a>:</h4>
<p>I've been using the following code successfully for several months:<br>
<code>catalog = intake.open_esm_datastore("/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.json")</code></p>
<p>I am now getting an error message <code>FileNotFoundError: [Errno 2] No such file or directory: 'glade-cmip6.csv.gz'</code></p>
<p>I've checked that the file exists in the directory, and I also update as suggested above: <code>pip install git+https://github.com/NCAR/intake-esm.git</code> and restarted the kernel. This fix does not work, and I get the same error message. Did something else change or get updated that I'm not aware of?</p>



<a name="19301"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19301" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19301">(Oct 12 2020 at 23:25)</a>:</h4>
<p><span class="user-mention" data-user-id="74">@Danica Lombardozzi</span> , </p>
<p>I am unable to reproduce the issue:</p>
<div class="codehilite"><pre><span></span><span class="n">In</span> <span class="p">[</span><span class="mi">1</span><span class="p">]:</span> <span class="kn">import</span> <span class="nn">intake</span>

<span class="n">In</span> <span class="p">[</span><span class="mi">2</span><span class="p">]:</span> <span class="n">catalog</span> <span class="o">=</span> <span class="n">intake</span><span class="o">.</span><span class="n">open_esm_datastore</span><span class="p">(</span><span class="s2">&quot;/glade/collections/cmip/catalog/intake-esm-datasto</span>
   <span class="o">...</span><span class="p">:</span> <span class="n">re</span><span class="o">/</span><span class="n">catalogs</span><span class="o">/</span><span class="n">glade</span><span class="o">-</span><span class="n">cmip6</span><span class="o">.</span><span class="n">json</span><span class="s2">&quot;)</span>

<span class="n">In</span> <span class="p">[</span><span class="mi">3</span><span class="p">]:</span> <span class="n">catalog</span><span class="o">.</span><span class="n">df</span><span class="o">.</span><span class="n">head</span><span class="p">()</span>
<span class="n">Out</span><span class="p">[</span><span class="mi">3</span><span class="p">]:</span>
  <span class="n">activity_id</span> <span class="n">institution_id</span>  <span class="o">...</span>     <span class="n">time_range</span>                                               <span class="n">path</span>
<span class="mi">0</span>  <span class="n">AerChemMIP</span>            <span class="n">BCC</span>  <span class="o">...</span>  <span class="mi">201501</span><span class="o">-</span><span class="mi">205512</span>  <span class="o">/</span><span class="n">glade</span><span class="o">/</span><span class="n">collections</span><span class="o">/</span><span class="n">cmip</span><span class="o">/</span><span class="n">CMIP6</span><span class="o">/</span><span class="n">AerChemMIP</span><span class="o">/</span><span class="n">BCC</span><span class="o">/</span><span class="n">B</span><span class="o">...</span>
<span class="mi">1</span>  <span class="n">AerChemMIP</span>            <span class="n">BCC</span>  <span class="o">...</span>  <span class="mi">201501</span><span class="o">-</span><span class="mi">205512</span>  <span class="o">/</span><span class="n">glade</span><span class="o">/</span><span class="n">collections</span><span class="o">/</span><span class="n">cmip</span><span class="o">/</span><span class="n">CMIP6</span><span class="o">/</span><span class="n">AerChemMIP</span><span class="o">/</span><span class="n">BCC</span><span class="o">/</span><span class="n">B</span><span class="o">...</span>
<span class="mi">2</span>  <span class="n">AerChemMIP</span>            <span class="n">BCC</span>  <span class="o">...</span>  <span class="mi">201501</span><span class="o">-</span><span class="mi">205512</span>  <span class="o">/</span><span class="n">glade</span><span class="o">/</span><span class="n">collections</span><span class="o">/</span><span class="n">cmip</span><span class="o">/</span><span class="n">CMIP6</span><span class="o">/</span><span class="n">AerChemMIP</span><span class="o">/</span><span class="n">BCC</span><span class="o">/</span><span class="n">B</span><span class="o">...</span>
<span class="mi">3</span>  <span class="n">AerChemMIP</span>            <span class="n">BCC</span>  <span class="o">...</span>  <span class="mi">201501</span><span class="o">-</span><span class="mi">205512</span>  <span class="o">/</span><span class="n">glade</span><span class="o">/</span><span class="n">collections</span><span class="o">/</span><span class="n">cmip</span><span class="o">/</span><span class="n">CMIP6</span><span class="o">/</span><span class="n">AerChemMIP</span><span class="o">/</span><span class="n">BCC</span><span class="o">/</span><span class="n">B</span><span class="o">...</span>
<span class="mi">4</span>  <span class="n">AerChemMIP</span>            <span class="n">BCC</span>  <span class="o">...</span>  <span class="mi">201501</span><span class="o">-</span><span class="mi">205512</span>  <span class="o">/</span><span class="n">glade</span><span class="o">/</span><span class="n">collections</span><span class="o">/</span><span class="n">cmip</span><span class="o">/</span><span class="n">CMIP6</span><span class="o">/</span><span class="n">AerChemMIP</span><span class="o">/</span><span class="n">BCC</span><span class="o">/</span><span class="n">B</span><span class="o">...</span>
</pre></div>


<p>and I can confirm that the necessary files are available:</p>
<div class="codehilite"><pre><span></span>abanihi at casper26 in /glade/collections/cmip/catalog/intake-esm-datastore/catalogs on master <span class="o">[</span>!<span class="o">]</span>
$ ls glade-cmip*
glade-cmip5.csv.gz  glade-cmip5.json  glade-cmip6.csv.gz  glade-cmip6.json
</pre></div>



<a name="19302"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19302" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19302">(Oct 12 2020 at 23:27)</a>:</h4>
<p>When you get a chance, could you post here the <strong>full traceback</strong> of the error you are getting?</p>



<a name="19303"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19303" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Danica Lombardozzi <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19303">(Oct 12 2020 at 23:34)</a>:</h4>
<p>Really? Well, I wonder what's going on. I'm having the same issue in two of my scripts. I've been using the CMIP62019.10a kernel. Below is more information on the problem I am encountering.</p>
<p>I import several functions:</p>
<div class="codehilite"><pre><span></span>import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import esmlab

#Tried below install, unsuccessful at fixing the intake error
#pip install git+https://github.com/NCAR/intake-esm.git

import intake
</pre></div>


<p>Then I attempt to import the data:</p>
<div class="codehilite"><pre><span></span>catalog = intake.open_esm_datastore(&quot;/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.json&quot;)
catalog.df.head()
</pre></div>


<p>Which results in the below error message</p>
<div class="codehilite"><pre><span></span>---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
&lt;ipython-input-3-1231c631f29f&gt; in &lt;module&gt;
----&gt; 1 catalog = intake.open_esm_datastore(&quot;/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.json&quot;)
      2 catalog.df.head()

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/intake_esm/core.py in __init__(self, esmcol_path, **kwargs)
     68         self.esmcol_path = esmcol_path
     69         self._col_data = _fetch_and_parse_file(esmcol_path)
---&gt; 70         self.df = self._fetch_catalog()
     71         self._entries = {}
     72         self.urlpath = &#39;&#39;

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/intake_esm/core.py in _fetch_catalog(self)
    113         &quot;&quot;&quot;Get the catalog file and cache it.
    114         &quot;&quot;&quot;
--&gt; 115         return pd.read_csv(self._col_data[&#39;catalog_file&#39;])
    116
    117     def nunique(self):

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    683         )
    684
--&gt; 685         return _read(filepath_or_buffer, kwds)
    686
    687     parser_f.__name__ = name

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    455
    456     # Create the parser.
--&gt; 457     parser = TextFileReader(fp_or_buf, **kwds)
    458
    459     if chunksize or iterator:

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    893             self.options[&quot;has_index_names&quot;] = kwds[&quot;has_index_names&quot;]
    894
--&gt; 895         self._make_engine(self.engine)
    896
    897     def close(self):

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1133     def _make_engine(self, engine=&quot;c&quot;):
   1134         if engine == &quot;c&quot;:
-&gt; 1135             self._engine = CParserWrapper(self.f, **self.options)
   1136         else:
   1137             if engine == &quot;python&quot;:

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1915         kwds[&quot;usecols&quot;] = self.usecols
   1916
-&gt; 1917         self._reader = parsers.TextReader(src, **kwds)
   1918         self.unnamed_cols = self._reader.unnamed_cols
   1919

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

/ncar/usr/jupyterhub/envs/cmip6-201910a/lib/python3.7/gzip.py in __init__(self, filename, mode, compresslevel, fileobj, mtime)
    161             mode += &#39;b&#39;
    162         if fileobj is None:
--&gt; 163             fileobj = self.myfileobj = builtins.open(filename, mode or &#39;rb&#39;)
    164         if filename is None:
    165             filename = getattr(fileobj, &#39;name&#39;, &#39;&#39;)

FileNotFoundError: [Errno 2] No such file or directory: &#39;glade-cmip6.csv.gz&#39;
</pre></div>



<a name="19304"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19304" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19304">(Oct 12 2020 at 23:45)</a>:</h4>
<p>Thank you, Danica! I now know what's going on <span aria-label="slight smile" class="emoji emoji-1f642" role="img" title="slight smile">:slight_smile:</span> </p>
<p>1) The environment  ( <code>cmip6-201910a</code>) you are using is outdated and unfortunately <code>pip install ....</code> doesn't have any effect towards fixing the issue </p>
<p>2) You actually want to use the <strong><code>cmip6-201910</code></strong> environment instead of <code>cmip6-201910a</code> (notice the <code>a</code> at the end). The <code>cmip6-2019</code> has an up-to-date version of <code>intake-esm</code> that knows how to resolve the absolute path of the <code>glade-cmip6-csv.gz</code> file when given the path to the JSON.</p>



<a name="19305"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19305" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Danica Lombardozzi <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19305">(Oct 12 2020 at 23:51)</a>:</h4>
<p>Aha! That did the trick! Thanks for the update. I thought that <code>cmip6-201910a</code> was the more up-to-date version, so it's good to know that I shouldn't use it.</p>



<a name="19307"></a>
<h4><a href="https://zulip2.cloud.ucar.edu#narrow/stream/10-python-questions/topic/intake-esm%20open%20dataset%20error/near/19307" class="zl"><img src="../../../assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Anderson Banihirwe <a href="../../..//stream/10-python-questions/topic/intake-esm.20open.20dataset.20error.html#19307">(Oct 13 2020 at 00:05)</a>:</h4>
<p>Awesome! </p>
<blockquote>
<p>I thought that cmip6-201910a was the more up-to-date version</p>
</blockquote>
<p>This was the original idea, however, for administrative reasons the two environments ended up diverging over time (as far as package versions are concerned)..<br>
I happen to have admin permissions on the <code>cmip6-2019</code> environment. As a result, I try to keep it up-to-date. However, I don't have control over the <code>cmip6-2019a</code> environment</p>



<hr><p>Last updated: May 16 2025 at 17:14 UTC</p>
</html>